M48
; DRILL file {KiCad (6.0.5-0)} date Sunday, October 30, 2022 at 11:15:54 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-30T23:15:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X3.556Y44.45
X3.556Y41.91
T2
X1.27Y34.29
X1.27Y31.75
X8.89Y34.29
X11.43Y34.29
X16.51Y34.29
X16.51Y31.75
T0
M30
